// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package app

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Page() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>eBPF Demo | Zeptor</title><script src=\"https://cdn.tailwindcss.com\"></script></head><body class=\"bg-gray-900 text-white min-h-screen\"><nav class=\"bg-gray-800 border-b border-gray-700\"><div class=\"container mx-auto px-4 py-3 flex items-center justify-between\"><a href=\"/\" class=\"text-xl font-bold text-blue-400\">Zeptor + eBPF</a></div></nav><main class=\"container mx-auto px-4 py-12\"><div class=\"text-center mb-12\"><h1 class=\"text-5xl font-bold mb-4\">eBPF Acceleration Enabled</h1><p class=\"text-xl text-gray-400\">Kernel-level packet routing and HTTP caching</p></div><div class=\"grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto\"><div class=\"bg-gray-800 p-6 rounded-lg border border-gray-700\"><h3 class=\"text-xl font-semibold mb-3 text-green-400\">XDP Router</h3><p class=\"text-gray-400 mb-4\">Packets processed at network driver level before reaching kernel network stack</p><div class=\"text-3xl font-bold text-green-400\">~50ns</div><p class=\"text-gray-500 text-sm\">per packet latency</p></div><div class=\"bg-gray-800 p-6 rounded-lg border border-gray-700\"><h3 class=\"text-xl font-semibold mb-3 text-blue-400\">TC Cache</h3><p class=\"text-gray-400 mb-4\">HTTP responses cached in eBPF maps for instant delivery</p><div class=\"text-3xl font-bold text-blue-400\">~100ns</div><p class=\"text-gray-500 text-sm\">cache hit latency</p></div></div><div class=\"mt-12 max-w-2xl mx-auto\"><div class=\"bg-gray-800 p-6 rounded-lg border border-gray-700\"><h3 class=\"text-lg font-semibold mb-4\">Cache Statistics</h3><p class=\"text-gray-400\">Visit <code class=\"bg-gray-900 px-2 py-1 rounded\">/api/stats</code> to see eBPF cache statistics</p></div></div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
